### ISSUE TITLE
Failure in Opening Auth0 Extension Through CLI

### ISSUE THREAD

**Issue by dantclee** [auth0-training/labs-node-working-with-apis#4]
### Description
![image](https://user-images.githubusercontent.com/59330585/213983606-42fed927-8ce6-46e9-af7c-1dd0964c4651.png)

When I click the hyperlink at the second point, I do not receive any feedback.  I expect Auth0 extension (if any) opens and view my tenant configuration.

### Reproduction

Go to step 2 of 2 of the code tour. Click the hyperlink at the first point, then the one at the second point. 

### Environment

> Please provide the following:

- **Version of this library used:** 1.1.1
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:**

**Comment by jesposito** [comment]
Hi Dan,

Do you have the Auth0 extension installed? It should install when the lab opens in Docker. See the screenshot below:
<img width="1227" alt="image" src="https://user-images.githubusercontent.com/6147236/214100125-dfd9d50f-44cc-4e85-adcb-c17f731d71a2.png">

**Comment by dantclee** [comment]
Hi Jedidith,

Yes, I have installed that extension.

Cheers,

Dan

**Comment by jesposito** [comment]
Hi Dan,

Hmm. Can you also confirm you're running the lab in Docker and went through the "sign-in" part of the tour? (The Auth0 plugin has authenticated with your Auth0 tenant)

If the answer to both of these is yes, I'd suggest resetting the lab. Here's how:

1. Close Visual Studio Code.

2. From your terminal, execute the following commands.

![image](https://user-images.githubusercontent.com/6147236/214181079-d765dbe9-2e9f-4630-8e84-f692533f0f8f.png)

The first command will reset any modified files to an unmodified state. The second command will remove any files or directories that have been added since the repository was cloned to the local machine. Combined the commands will return the lab repository to the same state it was in when freshly cloned.

3. Once completed, start the lab up again, reopen it in Docker, click "configure" when it shows up (lower right in VS code) and you should start up in the "Sign in" part of the lab.

Let me know how this goes!

**Comment by dantclee** [comment]
Hi Jedidith,

Issue solved.  Thank you.

Cheers,
Dan
